### ISSUE TITLE
Bug in ribORF.pl

### ISSUE THREAD

**Issue by JC-therea** [zhejilab/RibORF#4]
Hello, I am using your last version of the program but I noticed one problem with the code. You changed the nomenclature on some scripts (for example internal -> iORF) but not in all of them. When I was building the glm model with ribORF.pl I noticed that previous nomenclature (internal) was used to build it producing that the most recent models were better than those with ribORF 1 because of this bug. 

The part of the R code that I am talking about is the following:

```
print RI "B1 <- A[grepl('canonical', A[,1]),]"."\n";
print RI "B2 <- A[grepl('internal', A[,1]),]"."\n"; 
print RI "B3 <- A[A\$PME < 0.1,]"."\n";
```
I would appreciate it if you change it.

**Comment by zhejilab** [comment]
I made the change. Thanks. Please let me know if it works now.
